name: extras

services:
  transmission:
    container_name: transmission
    image: docker.io/linuxserver/transmission:4.0.4
    env_file:
      - .env
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    # volumes:
    #   - /DATA/AppData/transmission/config:/config
    #   - /DATA/Downloads:/downloads
    #   - /DATA/Downloads/watch:/watch
    environment:
      # - USER=${TRANSMISSION_USERNAME:-transmission}
      # - PASS=${TRANSMISSION_PASSWORD:-transmission}
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - PEERPORT=51413
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M

  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      TITLE: "LibreSpeed"
      TELEMETRY: "false"
      ENABLE_ID_OBFUSCATION: "false"
      REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    ports:
      - "8080:8080"
    networks:
      - cloudflare_tunnel
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M