
version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    command: --label-enable --cleanup

    # npm:
    #   container_name: nginx-proxy-manager
    #   image: 'docker.io/jc21/nginx-proxy-manager:latest'
    #   restart: unless-stopped
    #   ports:
    #     - '80:80'
    #     - '81:81'
    #     - '443:443'
    #   volumes:
    #     - ./data:/data
    #     - ./letsencrypt:/etc/letsencrypt